/*
|--------------------------------------------|
         ⚡️ Generated by Agentsmith ⚡️
      ⚠️ Do not edit this file directly ⚠️
|--------------------------------------------|
*/
export type Agency = {
    prompts: {
        'transcript-cleanup': {
            uuid: '902301a8-0a99-483a-9c9e-020a89cf6e62';
            name: 'Transcript Cleanup';
            slug: 'transcript-cleanup';
            versions: {
                'latest': { uuid: '45851eca-a94c-4ff8-bc68-468bcfaf17f9'; version: '0.0.1'; config: any; content: string; variables: { 'transcription': string } };
                '0.0.1': { uuid: '45851eca-a94c-4ff8-bc68-468bcfaf17f9'; version: '0.0.1'; config: any; content: string; variables: { 'transcription': string } }
            }
        };
        'claim-extraction': {
            uuid: '78e20565-75de-4bf9-a54d-444727d66eed';
            name: 'Claim Extraction';
            slug: 'claim-extraction';
            versions: {
                'latest': { uuid: 'ba1ae2d1-36e1-4383-b851-2d650aafa134'; version: '0.0.1'; config: any; content: string; variables: { 'transcript': string } };
                '0.0.1': { uuid: 'ba1ae2d1-36e1-4383-b851-2d650aafa134'; version: '0.0.1'; config: any; content: string; variables: { 'transcript': string } }
            }
        };
        'supporting-citations-search': {
            uuid: '6bb78908-1994-4257-a550-3a5d51ff3da4';
            name: 'Supporting Citations Search';
            slug: 'supporting-citations-search';
            versions: {
                'latest': { uuid: '5a3ae250-95d8-44b9-ae88-13711e96d6b1'; version: '0.0.1'; config: any; content: string; variables: { 'claims': any } };
                '0.0.1': { uuid: '5a3ae250-95d8-44b9-ae88-13711e96d6b1'; version: '0.0.1'; config: any; content: string; variables: { 'claims': any } }
            }
        };
        'outline-formatter': {
            uuid: '7bac2850-7c48-44f1-99a0-b76e371d96d9';
            name: 'Outline Formatter';
            slug: 'outline-formatter';
            versions: {
                'latest': { uuid: '79571027-eb35-4493-afa3-e4451ec2ef74'; version: '0.0.1'; config: any; content: string; variables: { 'transcript': string; 'citations': string } };
                '0.0.1': { uuid: '79571027-eb35-4493-afa3-e4451ec2ef74'; version: '0.0.1'; config: any; content: string; variables: { 'transcript': string; 'citations': string } }
            }
        }
    };
    globals: {}
};
