-- Functions
create or replace function set_updated_at()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

-- Wordweaver Users
create table ww_users (
    id bigint generated by default as identity not null primary key,
    auth_user_id uuid references auth.users(id) not null,
    email text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create policy "Users can view their own record"
    on ww_users for select
    to authenticated
    using (auth_user_id = (SELECT auth.uid()));

create trigger trigger_updated_at_ww_users
    before update on ww_users
    for each row
    execute function set_updated_at();


-- Auto-create ww_users record when auth.users record is created
create or replace function create_ww_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  var_ww_user_id bigint;
begin
    -- create the ww_users record
    insert into public.ww_users (auth_user_id, email)
    values (new.id, new.email)
    returning id into var_ww_user_id;

    return new;
end;
$$;

create trigger trigger_create_ww_user
    after insert on auth.users
    for each row
    execute function create_ww_user();

